import shelve

level_map_1 = [
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          XXXXXXXXXXXXXXXXXXXXXXXX ',
'XXXX  XXXXXXXXXXXXXXXXXXX     YYY  YYYYYYYYYYY           XXXXXXXXX ',
'XXX      XXXXXXXXXXXX       YYYYY  YYYYYYYYYYY             YYXXXXX ',
'XX          XXXXXX         YYYYYY   YYYYYYYYY             YYY   XX ',
'XX            XXX          YYYYY    YYYYYYYYY            YYYY   XX ',
'XXP                       XXYYYY XXXXYYYYYYY            YYYY    XX ',
'XXX                       XXXYY  XXXXYYXXXXXXXXX  XXXX  YYY     XX ',
'XXX                       XXXXX      YYXXXXXXXXX  XXXXXXXYY     XX ',
'XXXX      XX               XXXX              XXX     XXXXXXXX   XX ',
'XXXX      XX       XX  XX      XXX           XXX        XXXXX   XX ',
'XXXXX  XXXXXB     XXX  XX      XXXX          XXX                XX ',
'XXXXX  XXXXX    XXXXX  XXSSSSSSXXXX   XXX    XXX                XX ',
'XXXXX  XXXXXXX  XXXXX  XXXXXXXXXXX    XXX    XXX            XXXXXX ',
'XXXXX  XXXXXXX  XXXXX  XXXXXXXXXX    XXXX    XXX            XXXXXX ',
'XXXXX  XXXXXXX  XXXXX  YYYYYYYYYYY  XXXXX    XXX      XX       OXX ',
'XXXXX  XXXXXXX  XXXXX  YYYYYYYYYYY  XXXXX    XXX   B  XX        XX ',
'XXXXX  XXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXX    XXX      XXXX  XXXXXX ',
'XXXXX  XXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXX    XXX  XX  XXXX  XXXXXX ',
'XXXXX  XXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXX    XXX  XX  XXXX  XXXXXX ',
'                                                                   ',
]


level_map_2 = [
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'XXXXX      XXXXXXXXXXXXXXXX                      XXXXXXX ',
'XXX                 XXXXXX                            XX ',
'XX                    XXX                             XX ',
'XX         XX         XXX               XX            XX ',
'XXP        XX          XX              XXXB           XX ',
'XXXX    XX XXX         XX              XXXX           XX ',
'XXXX    XX XXX         XX             XXXXX        O  XX ',
'XXXX    XX XXXXSSSSXXYYXX            XXXXXX           XX ',
'XXXX    XX XXXXXXXXXXYYXX            XXXXX        XX  XX ',
'XXXX    XX XXXXXXXXXXYYXX     XXXXX           XX  XX  XX ',
'XXXX    XX XXXXYYYYYYYYXX    XXXXXXX          XX  XX  XX ',
'XXXX    XX XXXXYYYYYYYYXX    XX  XXX      XX  XX  XX  XX ',
'XXXX    XX XXXXYYXXXXSSXXX      B XX     XXX  XX  XX  XX ',
'XXXX    XX XXXXYYXXXXXXXXX        XXX    XXX  XX  XX  XX ',
'XXXX    XX XXXXYYXXXXXXXX   XXXXXXXXX    XXX  XX  XX  XX ',
'XXXX    XX XXXXYY  YYYYYY   XXXXXXXXX   XXXX  XX  XX  XX ',
'XXXX    XX XXXXYY  YYYYYY  XXXXXXXXXX   XXXX  XX  XX  XX ',
'XXXX    XX XXXXXXXXXXXXXXX XXXXXXXXXX  XXXXX  XX  XX  XX ',
'XXXX    XX XXXXXXXXXXXXXXX XXXXXXXXXX  XXXXX  XX  XX  XX ',
'                                                         ',
]

level_map_3 = [
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'XXXX   XXXXXXXXXXX                                       XXXXXX ',
'XXX     XXXXXX                                              XXX ',
'XXX     XXXXX                                                XX ',
'XX       XXXX    XXXXX      XXX      XXX      XXX            XX ',
'XXP      XXXX    XXXXXX     XXXX     XXXX     XXXX          OXX ',
'XXXX     XXXXX      XXX     XXXX     XXXX     XXXX           XX ',
'XXXXX     XXXX       XX                                 XXXXXXX ',
'XXXXXS    XXXXX      XXX                                XXXXXXX ',
'XXXXXX    XXXXXX   XXXXX                                XXXXXXX ',
'XXXXXXS   XXXXXX   XXXXXX                              XXXXXXXX ',
'XXXXXXX    XXXX   XXXXXXX                              XXXXXXXX ',
'XXXXXXX     XX    XXXXXXXX                            XXXXXXXXX ',
'XXXXXXXX         XXXXXXXXX                            XXXXXXXXX ',
'XXXXXXXX       XXXXXXXXXXXX                          XXXXXXXXXX ',
'XXXXXXXX   XXXXXXXXXXXXXXXXX                        XXXXXXXXXXX ',
'XXXXXXXX   XXXXXXXXXXXXXXXXXXX                    XXXXXXXXXXXXX ',
'XXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'XXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'                                                               '
]

level_map_4 = [
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'XXXX   XXXXXXXXXXX                                       XXXXXX ',
'XXX     XXXXXX                                              XXX ',
'XXX     XXXXX                                                XX ',
'XX       XXXX    XXXXX      XXX      XXX      XXX            XX ',
'XXP      XXXX    XXXXXX     XXXX     XXXX     XXXX          OXX ',
'XXXX     XXXXX      XXX     XXXX     XXXX     XXXX           XX ',
'XXXXX     XXXX       XX                                 XXXXXXX ',
'XXXXXS    XXXXX      XXX                                XXXXXXX ',
'XXXXXX    XXXXXX   XXXXX                                XXXXXXX ',
'XXXXXXS   XXXXXX   XXXXXX                              XXXXXXXX ',
'XXXXXXX    XXXX   XXXXXXX                              XXXXXXXX ',
'XXXXXXX     XX    XXXXXXXX                            XXXXXXXXX ',
'XXXXXXXX         XXXXXXXXX                            XXXXXXXXX ',
'XXXXXXXX       XXXXXXXXXXXX                          XXXXXXXXXX ',
'XXXXXXXX   XXXXXXXXXXXXXXXXX                        XXXXXXXXXXX ',
'XXXXXXXX   XXXXXXXXXXXXXXXXXXX                    XXXXXXXXXXXXX ',
'XXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'XXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'                                                               '
]

level_map_5 = [
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'XXXX   XXXXXXXXXXX                                       XXXXXX ',
'XXX     XXXXXX                                              XXX ',
'XXX     XXXXX                                                XX ',
'XX       XXXX    XXXXX      XXX      XXX      XXX            XX ',
'XXP      XXXX    XXXXXX     XXXX     XXXX     XXXX          OXX ',
'XXXX     XXXXX      XXX     XXXX     XXXX     XXXX           XX ',
'XXXXX     XXXX       XX                                 XXXXXXX ',
'XXXXXS    XXXXX      XXX                                XXXXXXX ',
'XXXXXX    XXXXXX   XXXXX                                XXXXXXX ',
'XXXXXXS   XXXXXX   XXXXXX                              XXXXXXXX ',
'XXXXXXX    XXXX   XXXXXXX                              XXXXXXXX ',
'XXXXXXX     XX    XXXXXXXX                            XXXXXXXXX ',
'XXXXXXXX         XXXXXXXXX                            XXXXXXXXX ',
'XXXXXXXX       XXXXXXXXXXXX                          XXXXXXXXXX ',
'XXXXXXXX   XXXXXXXXXXXXXXXXX                        XXXXXXXXXXX ',
'XXXXXXXX   XXXXXXXXXXXXXXXXXXX                    XXXXXXXXXXXXX ',
'XXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'XXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'                                                               '
]

level_map_6 = [
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'XXXX   XXXXXXXXXXX                                       XXXXXX ',
'XXX     XXXXXX                                              XXX ',
'XXX     XXXXX                                                XX ',
'XX       XXXX    XXXXX      XXX      XXX      XXX            XX ',
'XXP      XXXX    XXXXXX     XXXX     XXXX     XXXX          OXX ',
'XXXX     XXXXX      XXX     XXXX     XXXX     XXXX           XX ',
'XXXXX     XXXX       XX                                 XXXXXXX ',
'XXXXXS    XXXXX      XXX                                XXXXXXX ',
'XXXXXX    XXXXXX   XXXXX                                XXXXXXX ',
'XXXXXXS   XXXXXX   XXXXXX                              XXXXXXXX ',
'XXXXXXX    XXXX   XXXXXXX                              XXXXXXXX ',
'XXXXXXX     XX    XXXXXXXX                            XXXXXXXXX ',
'XXXXXXXX         XXXXXXXXX                            XXXXXXXXX ',
'XXXXXXXX       XXXXXXXXXXXX                          XXXXXXXXXX ',
'XXXXXXXX   XXXXXXXXXXXXXXXXX                        XXXXXXXXXXX ',
'XXXXXXXX   XXXXXXXXXXXXXXXXXXX                    XXXXXXXXXXXXX ',
'XXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'XXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'                                                               '
]

level_map_7 = [
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'XXXXX                                                               XX ',
'XXX                                                                 XX ',
'XX                            XXXXXXXXXXXXX                      XXXXX ',
'XX                          XXXXXXXXXXXXXXXX                    XXXXXX ',
'XX                         XXXXX       XXXXX                   XXXXXXX ',
'XXP      XX   XXXXXX     XXXXX          XXXX                  XXXXXXXX ',
'XXX     XXX   XXXXXXX  XXXXXX    XXX     XXXX                 XXXXXXXX ',
'XXXX  XXXXX       XXXSSXXXX    XXXXXX    XXXX                XXXXXXXXX ',
'XXXX  XXXXXX      XXXXXXXX    XXXXXXXX   XXXX                XXXXXXXXX ',
'XXXX  XXXXXXXXXXXXXXXXXXX    XXXXXXXXX   XXXX               XXXXXXXXXX ',
'XXXX   XXXXXXXXXXXXXX       XXXXXXXXXXX  XXXX               XXXXXXXXXX ',
'XXXX    XXXXXXXXXX         XXXXXXXXXXXX  XXXX              XXXXXXXXXXX ',
'XXXX                      XXXXXXXXXXXXX  XXXX              XXXXXXXXXXX ',
'XXXXX                   XXXXXXXXXXXXXX   XXXX             XXXXXXXXXXXX ',
'XXXXXXXXXXX           XXXXXXXXXXXXXXX    XXXXX            XXXXXXXXXXXX ',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXX           XXXXXXXXXXXXX ',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXX           XXXXXX           XXXXXXXXXXXXX ',
'XXO                                    XXXXXXXX         XXXXXXXXXXXXXX ',
'XX                                  XXXXXXXXXXXX       XXXXXXXXXXXXXXX ',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'                                                                       ',
]

level_map_8 = [
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'XXXX   XXXXXXXXXXX                                       XXXXXX ',
'XXX     XXXXXX                                              XXX ',
'XXX     XXXXX                                                XX ',
'XX       XXXX    XXXXX      XXX      XXX      XXX            XX ',
'XXP      XXXX    XXXXXX     XXXX     XXXX     XXXX          OXX ',
'XXXX     XXXXX      XXX     XXXX     XXXX     XXXX           XX ',
'XXXXX     XXXX       XX                                 XXXXXXX ',
'XXXXXS    XXXXX      XXX                                XXXXXXX ',
'XXXXXX    XXXXXX   XXXXX                                XXXXXXX ',
'XXXXXXS   XXXXXX   XXXXXX                              XXXXXXXX ',
'XXXXXXX    XXXX   XXXXXXX                              XXXXXXXX ',
'XXXXXXX     XX    XXXXXXXX                            XXXXXXXXX ',
'XXXXXXXX         XXXXXXXXX                            XXXXXXXXX ',
'XXXXXXXX       XXXXXXXXXXXX                          XXXXXXXXXX ',
'XXXXXXXX   XXXXXXXXXXXXXXXXX                        XXXXXXXXXXX ',
'XXXXXXXX   XXXXXXXXXXXXXXXXXXX                    XXXXXXXXXXXXX ',
'XXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'XXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'                                                               '
]

level_map_9 = [
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX         ',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        S',
'XX                                          XX         ',
'XX                                          XX         ',
'XXP                                         XX         ',
'XXXX  XX  XX  XX  XX  XX  XX  XX  XX  XX  XXXX         ',
'XXXX  XX  XX  XX  XX  XX  XX  XX  XX  XX  XXXX         ',
'XXXX  XX  XX  XX  XX  XX  XX  XX  XX  XX  XXXX         ',
'XXXX  XX  XX  XX  XX  XX  XX  XX  XX  XX  XXXX         ',
'XXXX  XX  XX  XX  XX  XX  XX  XX  XX  XX  XXXX         ',
'XXXX  XX  XX  XX  XX  XX  XX  XX  XX  XX  XXXX         ',
'XXXXSSXXSSXXSSXXSSXX  XXSSXXSSXXSSXXSSXXSSXXXX         ',
'XXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX         ',
'XXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX         ',
'XX                                          XX         ',
'XX                                          XX         ',
'XX                                          XX         ',
'XX  XX  XX  XX  XX  XX  XX  XX  XX  XX  XXXXXX         ',
'XX  XX  XX  XX  XX  XX  XX  XX  XX  XX  XXXXXX         ',
'XX  XX  XX  XX  XX  XX  XX  XX  XX  XX  XXXXXX         ',
'XX  XX  XX  XX  XX  XX  XX  XX  XX  XX  XXXXXX         ',
'XXSSXXSSXXSSXXSSXXSSXXSSXXSSXX  XXSSXXSSXXXXXX         ',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXX         ',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXX         ',
'XX                                          XX         ',
'XX                                          XX         ',
'XX                                          XX         ',
'XXXX  XX  XX  XX  XX  XX  XX  XX  XX  XX  XXXX         ',
'XXXX  XX  XX  XX  XX  XX  XX  XX  XX  XX  XXXX         ',
'XXXX  XX  XX  XX  XX  XX  XX  XX  XX  XX  XXXX         ',
'XXXX  XX  XX  XX  XX  XX  XX  XX  XX  XX  XXXX         ',
'XXXXSSXX  XXSSXXSSXXSSXXSSXXSSXXSSXXSSXXSSXXXX         ',
'XXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX         ',
'XXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX         ',
'XX                                          XX         ',
'XX                                          XX         ',
'XX                                          XX         ',
'XX  XX  XX  XX  XX  XX  XX  XX  XX  XX  XXXXXX         ',
'XX  XX  XX  XX  XX  XX  XX  XX  XX  XX  XXXXXX         ',
'XX  XX  XX  XX  XX  XX  XX  XX  XX  XX  XXXXXX         ',
'XX  XX  XX  XX  XX  XX  XX  XX  XX  XX  XXXXXX         ',
'XXSSXXSSXXSSXXSSXXSSXX  XXSSXXSSXXSSXXSSXXXXXX         ',
'XXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXX         ',
'XXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXX         ',
'XX                                         OXX         ',
'XX                                          XX         ',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX         ',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX         ',
'                                                       ',
]

#open the text file and asign leaderboard
leaderboard = shelve.open("leaderboard.db")
leaderboard_level_1 = leaderboard["1"]
leaderboard_level_2 = leaderboard["2"]
leaderboard_level_3 = leaderboard["3"]
leaderboard.close()
#leaderboard_level_1 = ['#1 :       Player1       -       999999 ', '#2 :       Player2       -       999999 ', '#3 :       Player3       -       999999 ', '#4 :       Player4       -       999999 ', '#5 :       Player5       -       999999 ']
#leaderboard_level_2 = ['#1 :       Player1       -       999999 ', '#2 :       Player2       -       999999 ', '#3 :       Player3       -       999999 ', '#4 :       Player4       -       999999 ', '#5 :       Player5       -       999999 ']
#leaderboard_level_3 = ['#1 :       Player1       -       999999 ', '#2 :       Player2       -       999999 ', '#3 :       Player3       -       999999 ', '#4 :       Player4       -       999999 ', '#5 :       Player5       -       999999 ']

screen_width = 1000
screen_height = 500